
internal_proxy_env: {}
internet_proxy_env: {}

user_name: sbower
user_home: "/home/{{user_name}}"
user_homedir: "{{user_home}}/.homedir"
user_bin: "{{user_homedir}}/bin"
user_bashrc: "{{user_homedir}}/.bashrc.d"
cache_directory: "{{user_homedir}}/.cache"

# GIT
git_user_name: stevenbower
git_user_email: smb-github@alcyon.net

# GOLANG
golang_version: "1.17.2"
golang_checksums:
  x86_64: "sha256:f242a9db6a0ad1846de7b6d94d507915d14062660616a61ef7c808a76e4f1676"
  aarch64: "sha256:a5a43c9cdabdb9f371d56951b14290eba8ce2f9b0db48fb5fc657943984fd4fc"

golang_architectures:
  x86_64: "amd64"
  aarch64: "arm64"
golang_arch: "{{ golang_architectures.get(ansible_architecture) }}"
golang_download_url: "https://golang.org/dl/go{{golang_version}}.linux-{{golang_arch}}.tar.gz"
golang_checksum: "{{ golang_checksums.get(ansible_architecture) }}"
golang_cache_directory: "{{cache_directory}}/golang"
golang_cache_file: "{{golang_cache_directory}}/golang.{{golang_version}}.tar.gz"
golang_base_dir: "{{user_bin}}/golang"
golang_version_path: "go-{{golang_version}}"
golang_bin_dir: "{{golang_base_dir}}/{{golang_version_path}}"

# Java
java_version: "11.0.7+10"
java_checksums:
  x86_64: "sha256:ee60304d782c9d5654bf1a6b3f38c683921c1711045e1db94525a51b7024a2ca"
  aarch64: "sha256:3b8b8bba6a0472ec7de5271cbf67f11e6ab525de6dd5d4729300375f1d56b7a1"

java_architectures:
  x86_64: "x64"
  aarch64: "aarch64"
java_arch: "{{ java_architectures.get(ansible_architecture) }}"
java_download_url: "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-{{java_version|replace('+','%2B')}}/OpenJDK11U-jdk_{{java_arch}}_linux_hotspot_{{java_version|replace('+','_')}}.tar.gz"
java_checksum: "{{ java_checksums.get(ansible_architecture) }}"
java_cache_directory: "{{cache_directory}}/java"
java_cache_file: "{{java_cache_directory}}/java.{{java_version}}.tar.gz"
java_base_dir: "{{user_bin}}/java"
java_version_path: "jdk-{{java_version}}"
java_bin_dir: "{{java_base_dir}}/{{java_version_path}}"

# Maven
maven_version: "3.8.4"
maven_download_url: "http://apache.mirrors.lucidnetworks.net/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz"
maven_checksum: "sha512:a9b2d825eacf2e771ed5d6b0e01398589ac1bfa4171f36154d1b5787879605507802f699da6f7cfc80732a5282fd31b28e4cd6052338cbef0fa1358b48a5e3c8"

maven_cache_directory: "{{java_cache_directory}}"
maven_cache_file: "{{maven_cache_directory}}/apache-maven-{{java_version}}.tar.gz"
maven_version_path: "apache-maven-{{maven_version}}"
maven_bin_dir: "{{java_base_dir}}/{{maven_version_path}}"

kubernetes:
  kubelet_version: 1.22.2-00
  kubeadm_version: 1.22.2-00
  kubectl_version: 1.22.2-00

# GCloud
gcloud_version: 299.0.0-0

# ProtoC
protoc_version: "3.11.4"

protoc_architectures:
  x86_64: "x86_64"
  aarch64: "aarch_64"
protoc_arch: "{{ protoc_architectures.get(ansible_architecture) }}"
protoc_download_url: "https://github.com/protocolbuffers/protobuf/releases/download/v{{protoc_version}}/protoc-{{protoc_version}}-linux-{{protoc_arch}}.zip"
protoc_cache_directory: "{{cache_directory}}/protoc"
protoc_cache_file: "{{protoc_cache_directory}}/protoc.{{protoc_version}}.zip"
protoc_base_dir: "{{user_bin}}/protoc"
protoc_version_path: "protoc-{{protoc_version}}"
protoc_bin_dir: "{{protoc_base_dir}}/{{protoc_version_path}}"

protoc_gen_go_version: "v1.25.0"
protoc_gen_go_download_url: "https://github.com/protocolbuffers/protobuf-go/releases/download/{{protoc_gen_go_version}}/protoc-gen-go.{{protoc_gen_go_version}}.linux.amd64.tar.gz"
protoc_gen_go_cache_file: "{{protoc_cache_directory}}/protoc-gen-go.{{protoc_gen_go_version}}.tar.gz"
protoc_gen_go_version_path: "protoc-gen-go-{{protoc_gen_go_version}}"
protoc_gen_go_bin_dir: "{{protoc_base_dir}}/{{protoc_gen_go_version_path}}"

# Ruby
ruby_version: "2.6.6"

ruby_download_url: "https://rvm.io/binaries/ubuntu/18.04/x86_64/ruby-{{ruby_version}}.tar.bz2"
ruby_cache_directory: "{{cache_directory}}/ruby"
ruby_cache_file: "{{ruby_cache_directory}}/ruby.{{ruby_version}}.tar.bz2"
ruby_base_dir: "{{user_bin}}/ruby"
ruby_version_path: "ruby-{{ruby_version}}"
ruby_bin_dir: "{{ruby_base_dir}}/{{ruby_version_path}}"

# NodeJS
nodejs_version: "v16.14.2"
nodejs_checksums:
  x86_64: "sha256:57e02c27eb5e52f560f72d96240e898cb52818dc9fc50f45478ce39ece38583a"
  aarch64: "sha256:8a792a4cb6d83a960f7bd2901225c492e40ace541fbd73ff59ac4a332c3aaafb"

nodejs_architectures:
  x86_64: "x64"
  aarch64: "arm64"

nodejs_arch: "{{ nodejs_architectures.get(ansible_architecture) }}"
nodejs_download_url: "https://nodejs.org/dist/{{nodejs_version}}/node-{{nodejs_version}}-linux-{{nodejs_arch}}.tar.gz"
nodejs_checksum: "{{ nodejs_checksums.get(ansible_architecture) }}"
nodejs_cache_directory: "{{cache_directory}}/nodejs"
nodejs_cache_file: "{{nodejs_cache_directory}}/nodejs.{{nodejs_version}}.tar.gz"
nodejs_base_dir: "{{user_bin}}/nodejs"
nodejs_version_path: "node-{{nodejs_version}}-linux-{{nodejs_arch}}"
nodejs_bin_dir: "{{nodejs_base_dir}}/{{nodejs_version_path}}"
